In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df = pd.read_csv('../Data/Cleaned_Data/airbnb_cleaned.csv')

In [4]:
df.head()

,listing_id,host_id,host_name,neighbourhood,city,room_type,property_type,price,minimum_nights,number_of_reviews,...,beds,bedrooms,bathrooms,guests,instant_bookable,cancellation_policy,host_response_rate,listing_status,device,payment_method
0,107345,10276,unknown,bronx,new york,hotel room,apartment,213.62,27,51,...,4.0,3.0,1.5,8.0,t,strict_14_with_grace_period,90.0,active,desktop,paypal
1,109454,5049,Emma,manhattan,new york,private room,guest suite,289.00,15,38,...,4.0,6.0,1.5,10.0,false,moderate,80.0,active,tablet,card
2,119857,11567,Sophia,manhattan,new york,private room,unknown,130.82,24,39,...,4.0,4.0,1.5,5.0,t,strict,90.0,active,mobile,card
3,108591,5546,unknown,queens,new york,entire home/apt,apartment,36.43,13,49,...,3.0,4.0,1.5,12.0,true,moderate,100.0,active,mobile,card
4,117164,8693,Michael,staten island,new york,entire home/apt,loft,271.74,21,41,...,10.0,3.0,1.5,4.0,t,moderate,85.0,available,mobile,cash

In [5]:
# Which neighbourhood earns the most on average, and which has the most listings?
df.groupby('neighbourhood')['price'].agg(['mean','count']).sort_values('mean',ascending = False)

                     mean  count
neighbourhood
bronx          223.382015   4015
staten island  220.898682   4091
queens         217.375870   3959
brooklyn       201.110251   3984
manhattan      186.769478   3946

In [8]:
# which room type performs best  - price vs demand?
df.groupby('room_type').agg(avg_price=('price','mean'),avg_reviews=('number_of_reviews','mean'))

                  avg_price  avg_reviews
room_type
entire home/apt  207.220289    45.045687
hotel room       193.813831    45.282638
private room     198.113534    45.012251
shared room      268.476416    44.833157

In [9]:
# Does a faster host response rate lead to a better rating?
df['host_response_rate'] = df['host_response_rate'].astype(str).str.replace("%","").astype(float)
df[['host_response_rate','rating']].corr()

                    host_response_rate    rating
host_response_rate            1.000000  0.002953
rating                        0.002953  1.000000

In [ ]:
# Does a stricter cancellation policy scare guests away?
df.groupby('cancellation_policy').agg(avg_reviews=('number_of_reviews','mean'),avg_price=('price','mean'))

                             avg_reviews   avg_price
cancellation_policy
flexible                       45.092770  203.669377
moderate                       45.083258  191.340535
strict                         44.820252  230.883529
strict_14_with_grace_period    45.043804  239.046562